variables:
  CI_DESIGNATED_BRANCH: prplos

include:
  - remote: https://gitlab.com/prpl-foundation/prplOS/prplos/-/raw/prplos/.gitlab/sdk.yml

generate:
  extends: .generate SDK package build jobs
  rules:
    - if: '$GITLAB_INTERNAL && $CI_COMMIT_REF_NAME == $INTERNAL_REF_BRANCH'
    - if: '$GITLAB_INTERNAL == null && $CI_COMMIT_REF_NAME == "main"'
    - if: '$GITLAB_INTERNAL == null && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    CI_SDK_TARGETS: |
      intel_mips-xrx500
      ath79-generic-19.07.7
      mvebu-cortexa9
      ipq40xx-generic
    CI_SDK_BUILD_PACKAGES: |
        libdhcpoptions
        libfwinterface
        libfwrules
        libnetmodel
        mod-dmext
        mod-dmstats
        mod-vlan-ioctl
        deviceinfo-manager
        dhcpv4-manager
        dhcpv6s-manager
        ethernet-manager
        ip-manager
        netdev-plugin
        netmodel
        pcm-manager
        routing-manager
        time-manager
        tr181-bridging
        tr181-device
        tr181-dhcpv4client
        tr181-dhcpv6client
        tr181-firewall
        tr181-usermanagement
        wan-manager

build:
  extends: .execute SDK package build jobs
  rules:
    - if: '$GITLAB_INTERNAL && $CI_COMMIT_REF_NAME == $INTERNAL_REF_BRANCH'
    - if: '$GITLAB_INTERNAL == null && $CI_COMMIT_REF_NAME == "main"'
    - if: '$GITLAB_INTERNAL == null && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"
