#!/bin/sh

if [[ -f "$IPKG_INSTROOT/etc/init.d/dnsmasq" ]]; then
    "${SHELL:-sh}" "$IPKG_INSTROOT/etc/rc.common" "$IPKG_INSTROOT/etc/init.d/dnsmasq" disable
    rm -f "$IPKG_INSTROOT/etc/init.d/dnsmasq"
fi

exit 0
