#!/bin/sh
# The modemmanager-prpl init script manages the ModemManager
# and ensures proper initialization and management of cellular manager's
# functionality in a PRPL environment:
#   - start/boot: Launches ModemManager-wrapper daemon
#   - stop/shutdown: Terminates the daemon via killall
#   - debuginfo: Shows modem information via mmcli -L
#   - restart: Performs stop followed by start

# Usage:
# - Install in /etc/init.d/modemmanager-prpl
# - Create symlinks in /etc/rc.d for automatic startup:
#   - S60modemmanager-prpl

[ -f /etc/environment ] && source /etc/environment
ulimit -c ${ULIMIT_CONFIGURATION:0}
name="ModemManager-wrapper"
LOG_LEVEL="INFO"

case $1 in
    start|boot)
        ${name} --log-level="$LOG_LEVEL" &
        ;;
    stop|shutdown)
        killall ${name}
        ;;
    debuginfo)
        mmcli -L
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage : $0 [start|boot|stop|shutdown|debuginfo|restart]"
        ;;
esac
