#!/bin/sh

# Remove OpenWRT-specific ModemManager scripts that are no longer needed

# Remove init script
rm -f /etc/init.d/modemmanager

# Remove protocol script
rm -f /lib/netifd/proto/modemmanager.sh

# Remove report down script
rm -f /usr/lib/ModemManager/connection.d/10-report-down

# Remove monitor script
rm -f /usr/sbin/ModemManager-monitor

# Adjust common script
sed -ie '/\/lib\/netifd\/netifd-proto.sh/d' /usr/share/ModemManager/modemmanager.common

exit 0